import type { AnimationState } from "./character";
import type { FurnitureItem } from "./furniture";
import type { RoomStatePayload } from "./roomState";

/** Walk to a spot, then place or move an object */
export interface SceneAction {
  type: "walk_then_place" | "walk_then_move";
  walkTo: { x: number; y: number };
  objectType?: string;
  objectId?: string;
  placementShifted?: boolean;
}

export type ActionStep =
  | {
      type: "walk";
      action: "walk_then_place" | "walk_then_move";
      walkTo: { x: number; y: number };
      objectType?: string;
      objectId?: string;
      placementShifted?: boolean;
    }
  | { type: "walk_home" }
  | { type: "build"; pendingIndex?: number }
  | { type: "player_stance"; stance: string };

/** Tone analysis payload sent by the backend with each AI response */
export interface CharacterTonePayload {
  /** Analyzed tone label, e.g. "empathetic", "playful" */
  tone: string;
  /** Sprite animation set to play while responding */
  animation: AnimationState;
  /** Optional frame URLs — overrides default animation config when provided */
  frames?: string[];
  speed?: number;
  loop?: boolean;
  /** Optional idle stance key for the player avatar when not moving */
  playerStance?: string;
}

export interface AiMessageResponse {
  id: string;
  content: string;
  timestamp: string;
  tone: CharacterTonePayload;
  /** Optional scene update bundled with the AI reply */
  roomState?: RoomStatePayload;
  /** Optional furniture generated by backend tools */
  furniture?: FurnitureItem[];
  /** Delay furniture/room updates until walk completes */
  deferredFurniture?: FurnitureItem[];
  deferredRoomState?: RoomStatePayload;
  /** Character walks to spot before object appears */
  sceneAction?: SceneAction;
  /** Ordered multi-step actions (walk, build, emote, etc.) */
  actionQueue?: ActionStep[];
  /** Preamble shown before image generation */
  pendingExecution?: boolean;
  /** Follow-up line after object creation finishes */
  postAction?: string;
}
